nelmio_api_doc:
    documentation:
        info:
            title: App third Party Adapter
            description: This is the documentation for App third Party Adapter
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
