#index:
#    path: /
#    controller: App\Controller\DefaultController::index

afrikpaysas_thirdparty_adapter:
  resource: '@AfrikpaysasSymfonyThirdpartyAdapterBundle/Resources/config/routes.yaml'

#afrikpaysas_thirdparty_adapter_app:
#  resource: '@AfrikpaysasSymfonyThirdpartyAdapterBundle/Resources/config/routes_app.yaml'
